### ISSUE TITLE
Error:Login required

### ISSUE THREAD

**Issue by railsfactory-subbulakshmi** [Bodacious/blogit#11]
undefined local variable or method `login_required' for #Blogit::PostsController:0xab9a7f8 when clicking on "new post"

**Comment by philou** [comment]
Did you specify your actual login method in blogit config ? Exemple, for devise :

``` ruby
config.authentication_method = :authenticate_user!
```

**Comment by railsfactory-subbulakshmi** [comment]
It's working fine.Thank for your reply
