### ISSUE TITLE
Dependency: pygmentize

### ISSUE THREAD

**Issue by gavinlaking** [Bodacious/blogit#13]
I'm getting two failing tests from a clean clone of the blogit repository:

```
rspec ./spec/lib/blogit/parsers/markdown_parser_spec.rb:18 # (1) 
rspec ./spec/lib/blogit/parsers/markdown_parser_spec.rb:22 # (2)
```

(1) Blogit::Parsers::MarkdownParser code highlighting requires pygmentize to run
(2) Blogit::Parsers::MarkdownParser code highlighting should highlight code if highlight_code_syntax is true

Is `pygmentize` a real dependency and if so, should the documentation for development reflect this?

**Comment by philou** [comment]
Hi Gavin,

Pygmentize is a real dependency used when needing code highlighting. I
think there is à page in the wiki stating it.

**Comment by gavinlaking** [comment]
Hi Philippe,

Thanks- I've updated the wiki with instructions for installing this dependency on Mac OS X. I'm still getting failing tests though:

```
/Users/gavinlaking/.rvm/gems/ruby-1.9.3-p125@global/gems/bundler-1.2.0/lib/bundler/rubygems_integration.rb:147:in 'block in replace_gem': pygmentize is not part of the bundle. Add it to Gemfile. (Gem::LoadError)
from /Users/gavinlaking/.rvm/gems/ruby-1.9.3-p125/bin/pygmentize:18:in '\<main\>'
from /Users/gavinlaking/.rvm/gems/ruby-1.9.3-p125/bin/ruby_noexec_wrapper:14:in 'eval'
from /Users/gavinlaking/.rvm/gems/ruby-1.9.3-p125/bin/ruby_noexec_wrapper:14:in '\<main\>'
```

Any ideas?

**Comment by gavinlaking** [comment]
Solved. Emptying my default gemset and re-running `bundle install` fixed the problem. All tests passing. Let's hack!

**Comment by Bodacious** [comment]
Thanks for letting us know @gavinlaking
