### ISSUE TITLE
Mass Assignment Error

### ISSUE THREAD

**Issue by bertomartin** [Bodacious/blogit#18]
When updating a post with active admin, I get this error: 

> Can't mass-assign protected attributes: blogger_type

**Comment by Bodacious** [comment]
@bertomartin - I've updated this on the master branch but it hasn't been released yet.

Until the next release, you could do either:

``` ruby
# create the post as a child of your blogger class:
@user.blog_posts.new(params[:post])
```

or ...

``` ruby
# Tell Bundler to use the current master branch (edge) version of blogit:
gem 'blogit', git: 'git@github.com:KatanaCode/blogit.git'
```

**Comment by bertomartin** [comment]
Thanks for the quick response.
