### ISSUE TITLE
Access application route helper in template file.

### ISSUE THREAD

**Issue by candland** [Bodacious/blogit#2]
I'm wondering if you've run across this. I want to use the same layout for the blog, which is working as expected. However, the application routes are not available. 

I tried adding this in the Blogit.configure block, which almost works, but it is rooted as blog/

``` ruby
module Blogit
  module ApplicationHelper
    # almost
    include Rails.application.routes.url_helpers
  end
end
```

**Comment by candland** [comment]
This is what I ended up doing for now: [rails routes used in an isolated engine](http://www.candland.net/2012/04/17/rails-routes-used-in-an-isolated-engine/)

**Comment by philou** [comment]
You can now use the inline_main_app_named_routes blogit configuration option to do this for you.
