### ISSUE TITLE
undefined method `current_user

### ISSUE THREAD

**Issue by pfcfernandez** [Bodacious/blogit#28]
I get this above when going to /blog any idea?

**Comment by Bodacious** [comment]
You'll have to define your own `current_user` method in **application_controller.rb** - sorry, I thought this was mentioned in the docs.

**Comment by pfcfernandez** [comment]
oh cool makes sense just wanted to make sure. I am using refinerycms and I
think it comes with divise for auth and roles.. I dont want anyone to be
posting to the blog
just people flag with admin in the database, any recomendation/advice?

Thanks!

On Fri, Mar 29, 2013 at 3:17 AM, Gavin Morrice notifications@github.comwrote:

> You'll have to define your own current_user method in *
> application_controller.rb\* - sorry, I thought this was mentioned in the
> docs.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/KatanaCode/blogit/issues/28#issuecomment-15635091
> .

## 

Chris Fernandez
PlayFirst Operations/DevOps
Cloud/Migration Team

**Comment by schory** [comment]
Did you eventually find a solution for letting only some users create new blog posts?
Facing the same problems right now myself...
