### ISSUE TITLE
Error when trying to create a new post for the first time?

### ISSUE THREAD

**Issue by borski** [Bodacious/blogit#29]
The "New Post" link takes me to /blog/assets?action=new&controller=blogit%2Fposts, which results in:

Routing Error
No route matches [GET] "/blog/assets"
Try running rake routes for more information on available routes.

Any idea why this is happening? If I go to /blog/posts/new manually, I see the form, but the action also goes to /blog/assets. Thoughts?

**Comment by Bodacious** [comment]
Weird! Would you mind posting the contents of your routes file?

**Comment by borski** [comment]
Sadly, I can't do that, but there isn't anything that references /assets at all.

**Comment by Bodacious** [comment]
OK

Well, does moving the `mount Blogit::Engine => "/blog"` to the top of your routes file make a difference?

**Comment by borski** [comment]
Nope. Tried that one. I can't work out what it would be - and the Internet hasn't been helpful either :(

Can I email you privately? May be able to share a little more detail that way. 
—
Michael "Borski" Borohovski
Co-Founder | Tinfoil Security
http://www.tinfoilsecurity.com
borski@tinfoilsecurity.com
Tel: 317-4BORSKI

Meet with me! http://meetwith.me/borski

**Comment by Bodacious** [comment]
Sure - team@katanacode.com

**Comment by Bodacious** [comment]
@borski I just tried installing blogit in a fresh Rails 3.2.13 - I don't see the error you're reporting.

**Comment by borski** [comment]
@Bodacious figured it out. I had the same issue as this guy: http://philippe.bourgau.net/rails-urlhelpers-mixup-when-using-rails-engin

The race condition is really bothersome - any idea why that's happening?

**Comment by Bodacious** [comment]
@philou is a contributor to blogit. Maybe he can offer some insight?

**Comment by philou** [comment]
Hi,

Sorry, I can't remember anymore what was happening inside of rails, i lost
quite some time to understand what was happening. When I removed the
include, it worked. I don't think rails expects us to explicitly include
the routes like that.

Philippe

**Comment by Bodacious** [comment]
@borski Are you still having this error?

Are you using route helper methods or :controller, and :action options in `link_to`?
