### ISSUE TITLE
get blog posts outside of engine..

### ISSUE THREAD

**Issue by sopwithpup** [Bodacious/blogit#3]
IE a list of new posts in a div somewhere

I've installed and am testing out your really good engine, but have hit a snag.

Its installed as suggested in your docs and mounted on /blog in my routes file.

I want a list of posts to show on the front page of my site but am not sure how to achieve this, can you give me a pointer.

(not really an issue I know :-) )

**Comment by damienrch** [comment]
I know this is likely no longer relevant to you. But for other users: be sure to check the specs directory and read through the test for how the engine is used. Fire up a console and test:

Blogit::Post.all

Sadly, it would appear the project is dead as we've not seen an update in 7 months, and I just started using it on a project so might have to go with something else or use a fork.

**Comment by Bodacious** [comment]
@damien-roche Thanks for your input, you're right - all of the Blogit models etc. are namespaced under the Blogit module (e.g. `Blogit::Post`)

Check out the documentation for more info on the Blogit models or poke through the code itself.

Apologies for the lack of updates during the past few months - we've been very busy. The project is still very much alive now though and we've seen some great contributions from @philou who's been added to the team this week!

**Comment by omrishiv** [comment]
Is there a way to use post_path(post) to get the url for a specific post? I can't figure out how to go about that. Specifically, I'm trying to get the url for each post to build a sitemap.

**Comment by Bodacious** [comment]
Sure - you have to prefix the blogit engine routes with `blogit`

So `post_url(post)` becomes `blogit.post_url(post)` and `posts_url` becomes `blogit.posts_url`.

Check out the site map that already comes with blogit (at `blogit.posts_url(format: :xml)`) - maybe that will suit your requirements?

**Comment by Bodacious** [comment]
If you're using blogit to handle the creating and updating of blog posts too then it'll automatically notify Google and Bing of the changes.

Check out this blog post for more info http://katanacode.com/blog/posts/4-blogit-version-0-7-0-released

**Comment by omrishiv** [comment]
I'm using sitemap_generator because I'm using mixed content (static, dynamic, and blogit posts). I'm trying to do something like this in the sitemap file:

  add '/news', :changefreq => 'daily', :priority => 0.9
  Blogit::Post.all.each do |n|
    add blogit.post_paths(n)
  end

I still can't quite figure out how to get it to generate the path

**Comment by Bodacious** [comment]
You've written post_paths (plural) here... is that a typo?

Either way, since it's a sitemap you'll want to be using URLs so try

`blogit.post_url(n)`

**Comment by omrishiv** [comment]
Yes, that was a typo, but now I'm getting: undefined local variable or method `blogit' for #SitemapGenerator::Interpreter:0x007feb54abf8f0

**Comment by Bodacious** [comment]
So, looking at [sitemap_generator's](https://github.com/kjvarga/sitemap_generator) README, it looks as though their DSL for building the sitemap isn't aware of Rails's routes. Do any of the routes work? Like `root_url`?

**Comment by omrishiv** [comment]
Yes, I'm using other model routes and they are getting generated correctly

**Comment by Bodacious** [comment]
OK - So the issue is, it's not able to access blogit's mounted routes...

Try including this in your sitemap generator file:

`include Blogit::Engine.app.url_helpers`

If that works, you should be able to access the blogit urls without having to use the `blogit` prefix

**Comment by Bodacious** [comment]
i.e.: `post_url(n)` should be enough

**Comment by omrishiv** [comment]
I figured that; however, doing the include as you suggested now throws a different error

undefined method `include' for #SitemapGenerator::Interpreter:0x007ff7db641560

**Comment by Bodacious** [comment]
Can I just check you're not calling that from within the block of code are you?

Assuming you're not, I can't think of any reason why include wouldn't be recognised. Not only is it valid ruby, it's used in their code for that class https://github.com/kjvarga/sitemap_generator/blob/master/lib/sitemap_generator/interpreter.rb

**Comment by omrishiv** [comment]
I trimmed and obscured a bit, but here:

``` ruby
require 'rubygems'
require 'sitemap_generator'
include Blogit::Engine.app.url_helpers

SitemapGenerator::Sitemap.default_host = "adf"
SitemapGenerator::Sitemap.sitemaps_host = "asdf"
SitemapGenerator::Sitemap.public_path = 'adf'
SitemapGenerator::Sitemap.sitemaps_path = ''
SitemapGenerator::Sitemap.adapter = SitemapGenerator::WaveAdapter.new
SitemapGenerator::Sitemap.create do
  add '/home', :changefreq => 'daily', :priority => 0.9
  add '/model', :changefreq => 'daily', :priority => 0.9
  Model.find(:all).each do |b|
    add model_url(b.permalink), :changefreq => 'weekly'
  end
  Blogit::Post.all.each do |n|
    add post_url(n)
  end
  add '/about', :changefreq => 'weekly'
end
#SitemapGenerator::Sitemap.ping_search_engines # called for you when you use the rake task
```

If I change it to this:

``` ruby
require 'rubygems'
require 'sitemap_generator'

SitemapGenerator::Sitemap.default_host = "adf"
SitemapGenerator::Sitemap.sitemaps_host = "asdf"
SitemapGenerator::Sitemap.public_path = 'adf'
SitemapGenerator::Sitemap.sitemaps_path = ''
SitemapGenerator::Sitemap.adapter = SitemapGenerator::WaveAdapter.new
SitemapGenerator::Sitemap.create do
  add '/home', :changefreq => 'daily', :priority => 0.9
  add '/model', :changefreq => 'daily', :priority => 0.9
  Model.find(:all).each do |b|
    add model_url(b.permalink), :changefreq => 'weekly'
  end
  Blogit::Post.all.each do |n|
    add Blogit::Engine.app.url_helpers.post_url(n)
  end
  add '/about', :changefreq => 'weekly'
end
#SitemapGenerator::Sitemap.ping_search_engines # called for you when you use the rake task
```

I now get:
 Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true. 

I added actionmailer default url options to my environments, but that doesn't fix the problem

**Comment by Bodacious** [comment]
It's not an ActionMailer issue - try setting:
`Rails.application.routes.default_url_options[:host] = "http://yourdomain.com"`

**Comment by omrishiv** [comment]
I figured that, but since I'd tried what you proposed and it didn't work, I figured I'd try it, that is to say, 
Rails.application.routes.default_url_options[:host] = "http://yourdomain.com" does not work :(

**Comment by davestephens** [comment]
Bit late to the party, but I got this working with the sitemap gem by doing the following:

``` ruby
Blogit::Post.all.each do |post|
  add Blogit::Engine.app.url_helpers.post_path(post), lastmod: post.updated_at
end
```

The gem does its own mashing to create the sitemap URLs, so it expects a path as an input and not a full URL, so post_path, not post_url is correct in this case.
