### ISSUE TITLE
undefined method `blogit_authenticate'

### ISSUE THREAD

**Issue by rakesh87** [Bodacious/blogit#35]
i am getting this error for blogit 0.6.0 and 0.8.0 both versions:

ActionController::RoutingError - undefined method `blogit_authenticate' for Blogit::CommentsController:Class:
  (gem) blogit-0.6.0/app/controllers/blogit/comments_controller.rb:4:in`class:CommentsController'
  (gem) blogit-0.6.0/app/controllers/blogit/comments_controller.rb:2:in `<module:Blogit>'
  (gem) blogit-0.6.0/app/controllers/blogit/comments_controller.rb:1:in`<top (required)>'
  (gem) activesupport-3.2.6/lib/active_support/dependencies.rb:469:in `load'
  (gem) activesupport-3.2.6/lib/active_support/dependencies.rb:469:in`block in load_file'
  (gem) activesupport-3.2.6/lib/active_support/dependencies.rb:639:in `new_constants_in'
  (gem) activesupport-3.2.6/lib/active_support/dependencies.rb:468:in`load_file'
  (gem) activesupport-3.2.6/lib/active_support/dependencies.rb:353:in `require_or_load'
  (gem) activesupport-3.2.6/lib/active_support/dependencies.rb:502:in`load_missing_constant'
  (gem) activesupport-3.2.6/lib/active_support/dependencies.rb:192:in `block in const_missing'
  (gem) activesupport-3.2.6/lib/active_support/dependencies.rb:190:in`each'
  (gem) activesupport-3.2.6/lib/active_support/dependencies.rb:190:in `const_missing'
  (gem) activesupport-3.2.6/lib/active_support/inflector/methods.rb:229:in`block in constantize'
  (gem) activesupport-3.2.6/lib/active_support/inflector/methods.rb:228:in `each'
  (gem) activesupport-3.2.6/lib/active_support/inflector/methods.rb:228:in`constantize'
  (gem) activesupport-3.2.6/lib/active_support/dependencies.rb:554:in `get'
  (gem) actionpack-3.2.6/lib/action_dispatch/routing/route_set.rb:69:in`controller_reference'
  (gem) actionpack-3.2.6/lib/action_dispatch/routing/route_set.rb:54:in `controller'
  (gem) actionpack-3.2.6/lib/action_dispatch/routing/route_set.rb:32:in`call'
  (gem) journey-1.0.4/lib/journey/router.rb:68:in `block in call'
  (gem) journey-1.0.4/lib/journey/router.rb:56:in`each'
  (gem) journey-1.0.4/lib/journey/router.rb:56:in `call'
  (gem) actionpack-3.2.6/lib/action_dispatch/routing/route_set.rb:600:in`call'
  (gem) railties-3.2.6/lib/rails/engine.rb:479:in `call'
  (gem) railties-3.2.6/lib/rails/railtie/configurable.rb:30:in`method_missing'
  (gem) journey-1.0.4/lib/journey/router.rb:68:in `block in call'
  (gem) journey-1.0.4/lib/journey/router.rb:56:in`each'
  (gem) journey-1.0.4/lib/journey/router.rb:56:in `call'
  (gem) actionpack-3.2.6/lib/action_dispatch/routing/route_set.rb:600:in`call'
  (gem) sass-3.1.20/lib/sass/plugin/rack.rb:54:in `call'
  (gem) better_errors-0.3.2/lib/better_errors/middleware.rb:51:in`app_call'
  (gem) better_errors-0.3.2/lib/better_errors/middleware.rb:45:in `call'
  (gem) bullet-4.1.5/lib/bullet/rack.rb:8:in`call'
  (gem) newrelic_rpm-3.4.1/lib/new_relic/rack/browser_monitoring.rb:12:in `call'
  (gem) newrelic_rpm-3.4.1/lib/new_relic/rack/developer_mode.rb:24:in`call'
  (gem) warden-1.2.1/lib/warden/manager.rb:35:in `block in call'
  (gem) warden-1.2.1/lib/warden/manager.rb:34:in`catch'
  (gem) warden-1.2.1/lib/warden/manager.rb:34:in `call'
  (gem) actionpack-3.2.6/lib/action_dispatch/middleware/best_standards_support.rb:17:in`call'
  (gem) rack-1.4.1/lib/rack/etag.rb:23:in `call'
  (gem) rack-1.4.1/lib/rack/conditionalget.rb:35:in`call'
  (gem) actionpack-3.2.6/lib/action_dispatch/middleware/head.rb:14:in `call'
  (gem) actionpack-3.2.6/lib/action_dispatch/middleware/params_parser.rb:21:in`call'
  (gem) actionpack-3.2.6/lib/action_dispatch/middleware/flash.rb:242:in `call'
  (gem) rack-1.4.1/lib/rack/session/abstract/id.rb:205:in`context'
  (gem) rack-1.4.1/lib/rack/session/abstract/id.rb:200:in `call'
  (gem) actionpack-3.2.6/lib/action_dispatch/middleware/cookies.rb:338:in`call'
  (gem) activerecord-3.2.6/lib/active_record/query_cache.rb:64:in `call'
  (gem) activerecord-3.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:473:in`call'
  (gem) actionpack-3.2.6/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  (gem) activesupport-3.2.6/lib/active_support/callbacks.rb:405:in`_run__385806723__call__274648105__callbacks'
  (gem) activesupport-3.2.6/lib/active_support/callbacks.rb:405:in `__run_callback'
  (gem) activesupport-3.2.6/lib/active_support/callbacks.rb:385:in`_run_call_callbacks'
  (gem) activesupport-3.2.6/lib/active_support/callbacks.rb:81:in `run_callbacks'
  (gem) actionpack-3.2.6/lib/action_dispatch/middleware/callbacks.rb:27:in`call'
  (gem) actionpack-3.2.6/lib/action_dispatch/middleware/reloader.rb:65:in `call'
  (gem) actionpack-3.2.6/lib/action_dispatch/middleware/remote_ip.rb:31:in`call'
  (gem) actionpack-3.2.6/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  (gem) actionpack-3.2.6/lib/action_dispatch/middleware/show_exceptions.rb:56:in`call'
  (gem) railties-3.2.6/lib/rails/rack/logger.rb:26:in `call_app'
  (gem) railties-3.2.6/lib/rails/rack/logger.rb:16:in`call'
  (gem) actionpack-3.2.6/lib/action_dispatch/middleware/request_id.rb:22:in `call'
  (gem) rack-1.4.1/lib/rack/methodoverride.rb:21:in`call'
  (gem) rack-1.4.1/lib/rack/runtime.rb:17:in `call'
  (gem) activesupport-3.2.6/lib/active_support/cache/strategy/local_cache.rb:72:in`call'
  (gem) rack-1.4.1/lib/rack/lock.rb:15:in `call'
  (gem) actionpack-3.2.6/lib/action_dispatch/middleware/static.rb:62:in`call'
  (gem) airbrake-3.1.2/lib/airbrake/rack.rb:42:in `call'
  (gem) airbrake-3.1.2/lib/airbrake/user_informer.rb:12:in`call'
  (gem) railties-3.2.6/lib/rails/engine.rb:479:in `call'
  (gem) railties-3.2.6/lib/rails/application.rb:220:in`call'
  (gem) railties-3.2.6/lib/rails/railtie/configurable.rb:30:in `method_missing'
  (gem) passenger-3.0.19/lib/phusion_passenger/rack/request_handler.rb:96:in`process_request'
  (gem) passenger-3.0.19/lib/phusion_passenger/abstract_request_handler.rb:516:in `accept_and_process_next_request'
  (gem) passenger-3.0.19/lib/phusion_passenger/abstract_request_handler.rb:274:in`main_loop'
  (gem) passenger-3.0.19/lib/phusion_passenger/rack/application_spawner.rb:206:in `start_request_handler'
  (gem) passenger-3.0.19/lib/phusion_passenger/rack/application_spawner.rb:171:in`block in handle_spawn_application'
  (gem) passenger-3.0.19/lib/phusion_passenger/utils.rb:470:in `safe_fork'
  (gem) passenger-3.0.19/lib/phusion_passenger/rack/application_spawner.rb:166:in`handle_spawn_application'
  (gem) passenger-3.0.19/lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
  (gem) passenger-3.0.19/lib/phusion_passenger/abstract_server.rb:206:in`start_synchronously'
  (gem) passenger-3.0.19/lib/phusion_passenger/abstract_server.rb:180:in `start'
  (gem) passenger-3.0.19/lib/phusion_passenger/rack/application_spawner.rb:129:in`start'
  (gem) passenger-3.0.19/lib/phusion_passenger/spawn_manager.rb:253:in `block (2 levels) in spawn_rack_application'
  (gem) passenger-3.0.19/lib/phusion_passenger/abstract_server_collection.rb:132:in`lookup_or_add'
  (gem) passenger-3.0.19/lib/phusion_passenger/spawn_manager.rb:246:in `block in spawn_rack_application'
  (gem) passenger-3.0.19/lib/phusion_passenger/abstract_server_collection.rb:82:in`block in synchronize'
  internal:prelude:10:in `synchronize'
  (gem) passenger-3.0.19/lib/phusion_passenger/abstract_server_collection.rb:79:in`synchronize'
  (gem) passenger-3.0.19/lib/phusion_passenger/spawn_manager.rb:244:in `spawn_rack_application'
  (gem) passenger-3.0.19/lib/phusion_passenger/spawn_manager.rb:137:in`spawn_application'
  (gem) passenger-3.0.19/lib/phusion_passenger/spawn_manager.rb:275:in `handle_spawn_application'
  (gem) passenger-3.0.19/lib/phusion_passenger/abstract_server.rb:357:in`server_main_loop'
  (gem) passenger-3.0.19/lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
  (gem) passenger-3.0.19/helper-scripts/passenger-spawn-server:99:in`<main>'

**Comment by Bodacious** [comment]
Please check out the example code referenced in the comment above.

Blogit seems to be working fine in that example app - could you please have a look there for guidance.

If you're still having an issue, could you share the code?
