### ISSUE TITLE
SQLite support

### ISSUE THREAD

**Issue by calebhaye** [Bodacious/blogit#36]
Seems like blogit markup parsing doesn't work with SQLite.

Not like anyone cares or anything, I just stumbled across the issue while setting up a test app.

**Comment by Bodacious** [comment]
Thanks @calebhaye :smile:

It _should_ work though - the markup parsing is completely separate from the record persistence. I'll look into this when I have a chance.

**Comment by Bodacious** [comment]
This seems to be working OK. If anyone else runs into this issue in future, please make sure you have pygments installed
