### ISSUE TITLE
blogit engine on heroku wont display blogs

### ISSUE THREAD

**Issue by dasibre** [Bodacious/blogit#43]
I can't seem to figure out why, I'm unable to get the posts index to show up on heroku. Heroku logs show a router error
 heroku[router]: at=info method=GET path=/blog/posts/

I can get to the index when there are no posts in the database. The moment i add a new post, i get the routing error. Is it a database issue, as heroku uses pg and i'm using sqllite on my dev machine.

NOTE:
I'm using active_admin with blogit, everything works fine on my local machine. I can add new post, edit, delete, view index page of posts. Would appreciate any help i can get..

**Comment by Bodacious** [comment]
@dasibre Are you still having this issue?

Could you give us more info? I've never worked with Heroku before

**Comment by philou** [comment]
Hi,

My app embeds the blogit engine and runs on heroku without issue. I can
have a look at my code tonight to see if I did something special though ...

Philippe

**Comment by Bodacious** [comment]
Thanks @philou

**Comment by philou** [comment]
It seems i had some routing errors when I first tried blogit. I even bloged
about it
http://Philippe.bourgau.net/rails-urlhelpers-mixup-when-using-rails-engin/

Hope this helps

**Comment by dasibre** [comment]
Thanks so much for the, responses.....i looked at the heroku logs and realized the issue was already addressed. It was related to the markdown parser which required Pygment to be installed.
