### ISSUE TITLE
Draft, Published States

### ISSUE THREAD

**Issue by prpetten** [Bodacious/blogit#44]
It didn't appear to me that there was any concept of a draft post.  One of the key features in most blogging tools is the ability to create a post in draft status, come back to it, and later publish it.

**Comment by Bodacious** [comment]
@prpetten You're right - this is a feature we're looking to add ASAP.

We're planning a release of version 1.0 which should include more features, Rails 4 support and better docs. 

It's just taking longer than expected trying to fit it in with our commitments to clients

**Comment by DeepAnchor** [comment]
+1 for this, thanks for all your hard work on this awesome engine!

**Comment by Bodacious** [comment]
Thanks for the feedback @DeepAnchor - working on updating blogit and should hopefully have a full-featured version 1 released by the end of the year :)

**Comment by jjeb** [comment]
@Bodacious: Is somebody working in this feature?, If not, I can help to implement it.

**Comment by Bodacious** [comment]
@jjeb - nobody has started yet. If you could help, that would be greatly appreciated

**Comment by jjeb** [comment]
@Bodacious I can work on it, Do you have any particular idea about this feature? something like how many states (draft, published, deleted??, any other)?, Does it makes sense to use the approach of a state machine or just a flag (in the case of only  two states)?, could you let me know what do you think about it, please?. Thanks in advance.

**Comment by Bodacious** [comment]
@jjeb Thanks for offering to do this.

Since we want blogit to be as customisable as possible, why don't we allow developers  to customise the states, and offer sensible defaults.

As an example off the top of my head:

``` ruby
  # in the config file

  # list of states for the Post state machine in order or lifecycle
  config.post_states = [ :draft, :published, :archive ]

  # list of states that will be visible to the public
  config.active_states  = [ :published ]

  # list of states that will hide the posts from the public.
  config.hidden_states = [ :draft, :archive ]
```

Does that make sense?

**Comment by jjeb** [comment]
@Bodacious Got it.

**Comment by Bodacious** [comment]
@jjeb Thanks again for this
