### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by creativecommunion** [Bodacious/blogit#5]
I've added the gem and mounted the engine here: 
mount Blogit::Engine => "/blog"

Now when I go to <my_app>/blog I get the following error:
undefined local variable or method `blogit_conf' for Blogit::PostsController:Class

**Comment by Jud** [comment]
+1 on this issue.

**Comment by JustinAiken** [comment]
mount Blogit::Engine => "/blog", :as => "blog" 
will fix this error; I'm stuck on the next error though

**Comment by philou** [comment]
The 'blogit_config' error is fixed with version 0.5.0
