### ISSUE TITLE
How to validate uniqueness in comments?

### ISSUE THREAD

**Issue by abrambailey** [Bodacious/blogit#52]
I would like to limit comments by uniqueness scoped by email. Is this possible?

**Comment by Bodacious** [comment]
Hi @funkdified - you could try extending the comments model in your own app:

``` ruby
# in your_app/app/models/blogit/comment.rb
module Blogit
  class Comment < ActiveRecord::Base
    validates_uniqueness_of :email
  end
end
```

**Comment by abrambailey** [comment]
Oh I meant more like `validates :body, :uniqueness => {:scope => :email}` but thanks I will do that. 

I was thinking this would stop people from accidentally submitting a comment twice.

I also noticed AJAX validation errors aren't shown to the user, unless this is something I changed by editing my views.

**Comment by abrambailey** [comment]
Ok weirdest thing in the world. After adding:

```
# in your_app/app/models/blogit/comment.rb
module Blogit
  class Comment < ActiveRecord::Base
    validates :body, :uniqueness => {:scope => :email}
  end
end
```

I get 

```
Mysql2::Error: Table 'hearingtracker_development.blogit_comments' doesn't exist: SHOW FULL FIELDS FROM `blogit_comments`
```

There seems to be a real issue with the `blogit_comments` versus `blog_comments` naming of the table columns. I don't understand how extending the comments model has caused this error. I noticed another weird error earlier while trying to fork this gem.. the fork wasn't compatible with my DB due to blogit versus blog naming.. But both the fork and the original gem were set to 0.8.0

**Comment by Bodacious** [comment]
The earlier versions of the gem had unconventional table names

There's a generator to update the tables:  I'm not at my computer just now and can't remember the exact naming but a quick `rails g` should show it

https://github.com/KatanaCode/blogit/blob/master/lib/generators/templates/rename_blogit_tables.rb

Sorry, I haven't updated the documentation to include this yet, it was supposed to be a part of the upcoming version 1.0.0
