### ISSUE TITLE
Rails 4 / 4.1 compatibility

### ISSUE THREAD

**Issue by dlupu** [Bodacious/blogit#56]
Hello, just wondering when will the `rails4` branch be merged into master?

**Comment by jamesosb** [comment]
Hi, Yea i'm just wondering the same thing. Just about to pull BlogIt in to a new project. Is it worth going with the rails4 version or the master?

**Comment by Bodacious** [comment]
Sorry guys - I haven't had any free time to devote to blogit recently.

I've created a temporary branch `rails4-tmp`

If you add the following to your Gemfile

`gem "blogit", github: "katanacode/blogit", branch: "rails4-tmp"`

Then you can use the rails4 version. Once I've merged in the changes and updated the gem, I'll delete that branch - so you'll get a warning (notification) when you run `bundle update`

**Comment by jamesosb** [comment]
Cheers Bodacious!

**Comment by mbhnyc** [comment]
Thanks! Excited to get started with this as well.

**Comment by mbhnyc** [comment]
Can you merge in the acts_as_taggable_on fixes into this branch? Currently appears to be blocking installs?
