### ISSUE TITLE
Not work  in Rails 4.0

### ISSUE THREAD

**Issue by amolplay** [Bodacious/blogit#59]
When  I use rails g blogit:install then it gives error as follow:-

You should not use the `match` method in your router without specifying an HTTP method.
If you want to expose your action to both GET and POST, add `via: [:get, :post]` option.
If you want to expose your action to GET, use `get` in the router:
  Instead of: match "controller#action"
  Do: get "controller#action"

**Comment by Bodacious** [comment]
Please use version 1.0.0.rc1

Sorry if this mail was brief - it was sent from my iPhone

**Comment by tfe** [comment]
What branch or tag was 1.0.0.rc1 built from? I want to fork from that point but I can't find that version number in any of the branches. Thanks!

**Comment by Bodacious** [comment]
It should be the current master branch 

Sorry if this mail was brief - it was sent from my iPhone

**Comment by danjohnson3141** [comment]
I had the same error and switching to "1.0.0.rc1" cleared it up.

Thanks!!
