### ISSUE TITLE
Error when creating new blog posts

### ISSUE THREAD

**Issue by ntomkin** [Bodacious/blogit#6]
ActiveModel::MassAssignmentSecurity::Error in Blogit::PostsController#create
Can't mass-assign protected attributes: title, body, tag_list

Rails 3.2.8, Ruby 1.9.3

Gems: Devise, Blogit

**Comment by jamesosb** [comment]
Try putting: 

accepts_nested_attributes_for :title, :body, :tag_list 

In your Posts model.

**Comment by Bodacious** [comment]
Hi guys - this issue was specific to Rails 3.2.8 and has been fixed in version 0.5.0

Thanks a lot for raising it, apologies for the late response
