### ISSUE TITLE
undefined method `this_blogger?'

### ISSUE THREAD

**Issue by markslight** [Bodacious/blogit#60]
Sorry I'm a relative newbie to Rails. I read somewhere that setting "config.author_edits_only = true" with ensure only the author of a blog can change it. However when I set this I get 
undefined method `this_blogger?'

I can see where it is using this_blogger in the code but i can't see where/how I'm supposed to set it?

**Comment by poussinxt** [comment]
I have the same problem.
It looks like it comes from the fact that the method 'this_blogger?' is in application_controller and not in application_helper (which would make it available in the views).

**Comment by Bodacious** [comment]
Closed as no longer a part of blogit master
