### ISSUE TITLE
beginner question: how to start?

### ISSUE THREAD

**Issue by estileiser** [Bodacious/blogit#61]
Hi! I'm a beginner over here so I hope you can bear with me.

I'm trying to figure out how to set up a blog. Do I just create a blank rails project and include blogit in my gemfile? Or am I also supposed to be setting up models etc.?

Thanks!

**Comment by ZirconCode** [comment]
Read the readme:
https://github.com/KatanaCode/blogit#installation
And this guide on rails engines (which blogit is) if you want more information:
http://guides.rubyonrails.org/engines.html#hooking-into-an-application

**Comment by estileiser** [comment]
Thanks! I read the readme and followed its instructions, but it looks like
some models need to be created. Is that correct?

If so, how is this a sample blog? What exactly is in blogit?

Thanks

**Comment by Bodacious** [comment]
@estileiser 

Blogit provide the blog post and comment models, as well as controllers with CRUD actions for posts and comments

In your own application, you should deifine a model whos role is to blog (could be User, Admin, Blogger etc.) and call the `blogs` method in there to define all of the associations etc.

Please have a look at the configuration file for full config options

**Comment by estileiser** [comment]
Thanks for your response! However, I still can't get it to work. I created
a user model and put the blogs method in there. What do I do now? I played
around for a while and can't figure this out...

**Comment by Bodacious** [comment]
Are you seeing any error messages?

Have you mounted the engine in your routes file?

Are you using the latest version?

``` ruby

gem "blogit", github: "katana_code/blogit", branch: "master"


Gavin Morrice / Managing Director

Katana Code Ltd

www.katanacode.com

gavin@gavinmorrice.com

+44 7787 432 733




----------------------------------------------------------




This message is confidential and may contain privileged information. If it is not for you please inform us then delete it.




Any information in this message that does not relate to the official business of Katana Code is neither given nor endorsed by Katana Code. This e-mail does not constitute nor form part of a contract or unilateral obligation. Internet e-mails are not necessarily secure. Katana Code does not accept responsibility for changes made to this message after it was sent or viruses transmitted through this e-mail or any attachment. You should carry out your own virus checking procedure before opening any attachment to this e-mail. The e-mail and IT systems of Katana Code are subject to random monitoring and recording by or on behalf of Katana Code.




Katana Code is a trading name of Katana Code Ltd (Company No. SC410908), Registered Office: Lodge House, Priory Lane, Dunfermline KY12 7DT, +44 845 519 4329, www.katanacode.com

On Thu, Oct 30, 2014 at 12:55 AM, estileiser <notifications@github.com>
wrote:

> Thanks for your response! However, I still can't get it to work. I created
> a user model and put the blogs method in there. What do I do now? I played
> around for a while and can't figure this out...
> On Wed, Oct 29, 2014 at 7:00 AM, Gavin Morrice <notifications@github.com>
> wrote:
>> @estileiser <https://github.com/estileiser>
>>
>> Blogit provide the blog post and comment models, as well as controllers
>> with CRUD actions for posts and comments
>>
>> In your own application, you should deifine a model whos role is to blog
>> (could be User, Admin, Blogger etc.) and call the blogs method in there
>> to define all of the associations etc.
>>
>> Please have a look at the configuration file for full config options
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/KatanaCode/blogit/issues/61#issuecomment-60904802>.
>>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/KatanaCode/blogit/issues/61#issuecomment-61030531
```

**Comment by estileiser** [comment]
Thanks for the reply!

1) No error messages.

2) I put this in my routes file: mount Blogit::Engine => "/blog"

3) This is the code in my gemfile (as per your readme): gem "blogit",
github: "katanacode/blogit", branch: "rails4-tmp"

What do I do now?

Thanks!

**Comment by Bodacious** [comment]
Use:

gem "blogit", "~> 1.0.0.rc1"

Add the macro "blogs" to your User model (or equivalent)

I presume you've installed the blogit config too? (In config/initializers/blogit.rb)

Go to http://localhost:3000/blog to make sure it's working and read the `blogit.rb` file for customisation 

Gavin Morrice / Managing Director

Katana Code Ltd

www.katanacode.com

gavin@gavinmorrice.com

+44 7787 432 733

---

This message is confidential and may contain privileged information. If it is not for you please inform us then delete it.

Any information in this message that does not relate to the official business of Katana Code is neither given nor endorsed by Katana Code. This e-mail does not constitute nor form part of a contract or unilateral obligation. Internet e-mails are not necessarily secure. Katana Code does not accept responsibility for changes made to this message after it was sent or viruses transmitted through this e-mail or any attachment. You should carry out your own virus checking procedure before opening any attachment to this e-mail. The e-mail and IT systems of Katana Code are subject to random monitoring and recording by or on behalf of Katana Code.

Katana Code is a trading name of Katana Code Ltd (Company No. SC410908), Registered Office: Lodge House, Priory Lane, Dunfermline KY12 7DT, +44 845 519 4329, www.katanacode.com

**Comment by Bodacious** [comment]
@estileiser We've released a new version of blogit. Please check out the documentation for more info.
