### ISSUE TITLE
Missing model Tagging?

### ISSUE THREAD

**Issue by johncox00** [Bodacious/blogit#65]
Just getting up and running. When I browse to /posts/new I get a SQLite error saying the "taggings" table is missing. I'm using 1.0.0rc1. Any advice?

Also, is there a general admin route? I didn't see anything obvious.

Thanks.

**Comment by aharrell** [comment]
I'm getting the same thing :(

**Comment by Bodacious** [comment]
Hi guys - have you installed fresh, or upgraded?

The gem depends on ActsAsTaggableOn

As a quick-fix for now, try adding [this file](https://github.com/KatanaCode/blogit/blob/master/spec/dummy/db/migrate/20140511174024_acts_as_taggable_on_migration.acts_as_taggable_on_engine.rb)

I'm going to take the day off tomorrow to bring Blogit up to date. I'd really appreciate your feedback on things that can be improved

**Comment by abhayathem** [comment]
I am also facing same issue with version 1.0.0rc1.

**Comment by aharrell** [comment]
That solved 1 problem, but then I also had to add a column to the tags table called taggings_count. So that gets it working, except comments aren't saved. I installed fresh.

**Comment by Bodacious** [comment]
@aharrell We've released a new version of Blogit.

This version has a few breaking changes but should fix the issue you were having.

The [upgrading guide](http://blogit.katanacode.com/doc/file.Upgrading.html) describes how your application should look—you might need to add a migration yourself to get there.

Please let me know if you're still having problems

**Comment by mebibou** [comment]
Any way this could be fixed for fresh installs? I just tried to start using this CMS, but so far I keep getting errors everywhere, this is a nightmare. Could you detail all steps to install from scratch? I don't think anyone should struggle installing a gem. FYI even for fresh installs I still had many config options that did not exist anymore, like `include_admin_actions`.

I'm installing on version `1.1.1`
