### ISSUE TITLE
Error while deploying to Heroku

### ISSUE THREAD

**Issue by nrtechbytes** [Bodacious/blogit#71]
Hi 

I am working on a web app which is deployed on Heroku.
My app's integration with blogit works absolutely fine on localhost.

However, it gives the below mentioned error while trying to push to Heroku.

Any ideas/suggestions would be much appreciated. 
Thanks in advance.

---

rake aborted!
remote:        Sass::SyntaxError: Invalid CSS after "": expected selector or at-rule, was "{"
remote:        (in /tmp/build_0a8078a9a3ce382baab4b5879b3fd68d/vendor/bundle/ruby/2.2.0/gems/blogit-1.1.1/app/assets/stylesheets/blogit/themes/default.css.map)
remote:        (sass):1
remote:        /tmp/build_0a8078a9a3ce382baab4b5879b3fd68d/vendor/bundle/ruby/2.2.0/gems/sass-3.4.15/lib/sass/scss/parser.rb:1162:in `expected'
remote:        /tmp/build_0a8078a9a3ce382baab4b5879b3fd68d/vendor/bundle/ruby/2.2.0/gems/sass-3.4.15/lib/sass/scss/parser.rb:1098:in`expected'
remote:        /tmp/build_0a8078a9a3ce382baab4b5879b3fd68d/vendor/bundle/ruby/2.2.0/gems/sass-3.4.15/lib/sass/scss/parser.rb:43:in `parse'
remote:        /tmp/build_0a8078a9a3ce382baab4b5879b3fd68d/vendor/bundle/ruby/2.2.0/gems/sass-3.4.15/lib/sass/engine.rb:403:in`_to_tree'
remote:        /tmp/build_0a8078a9a3ce382baab4b5879b3fd68d/vendor/bundle/ruby/2.2.0/gems/sass-3.4.15/lib/sass/engine.rb:278:in `render'
remote:        /tmp/build_0a8078a9a3ce382baab4b5879b3fd68d/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/sass_compressor.rb:24:in`evaluate'
remote:        /tmp/build_0a8078a9a3ce382baab4b5879b3fd68d/vendor/bundle/ruby/2.2.0/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
remote:        /tmp/build_0a8078a9a3ce382baab4b5879b3fd68d/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/context.rb:197:in`block in evaluate'
remote:        /tmp/build_0a8078a9a3ce382baab4b5879b3fd68d/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/context.rb:194:in `each'
remote:        /tmp/build_0a8078a9a3ce382baab4b5879b3fd68d/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/context.rb:194:in`evaluate'
remote:        /tmp/build_0a8078a9a3ce382baab4b5879b3fd68d/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/bundled_asset.rb:25:in `initialize'
remote:        /tmp/build_0a8078a9a3ce382baab4b5879b3fd68d/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/base.rb:377:in`new'
remote:        /tmp/build_0a8078a9a3ce382baab4b5879b3fd68d/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/base.rb:377:in `build_asset'
remote:        /tmp/build_0a8078a9a3ce382baab4b5879b3fd68d/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/index.rb:94:in`block in build_asset'
remote:        /tmp/build_0a8078a9a3ce382baab4b5879b3fd68d/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/caching.rb:58:in `cache_asset'
remote:        /tmp/build_0a8078a9a3ce382baab4b5879b3fd68d/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/index.rb:93:in`build_asset'
remote:        /tmp/build_0a8078a9a3ce382baab4b5879b3fd68d/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/base.rb:287:in `find_asset'
remote:        /tmp/build_0a8078a9a3ce382baab4b5879b3fd68d/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/index.rb:61:in`find_asset'
remote:        /tmp/build_0a8078a9a3ce382baab4b5879b3fd68d/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/manifest.rb:211:in `block in find_asset
remote:        /tmp/build_0a8078a9a3ce382baab4b5879b3fd68d/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/manifest.rb:257:in`benchmark'
remote:        /tmp/build_0a8078a9a3ce382baab4b5879b3fd68d/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/manifest.rb:210:in `find_asset'
remote:        /tmp/build_0a8078a9a3ce382baab4b5879b3fd68d/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/manifest.rb:119:in`block in compile'
remote:        /tmp/build_0a8078a9a3ce382baab4b5879b3fd68d/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/manifest.rb:118:in `each'
remote:        /tmp/build_0a8078a9a3ce382baab4b5879b3fd68d/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/manifest.rb:118:in`compile'
remote:        /tmp/build_0a8078a9a3ce382baab4b5879b3fd68d/vendor/bundle/ruby/2.2.0/gems/sprockets-rails-2.3.2/lib/sprockets/rails/task.rb:70:in `block (3 levels) in define'
remote:        /tmp/build_0a8078a9a3ce382baab4b5879b3fd68d/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/rake/sprocketstask.rb:146:in`with_logger'
remote:        /tmp/build_0a8078a9a3ce382baab4b5879b3fd68d/vendor/bundle/ruby/2.2.0/gems/sprockets-rails-2.3.2/lib/sprockets/rails/task.rb:69:in `block (2 levels) in define'
remote:        Tasks: TOP => assets:precompile
remote:        (See full trace by running task with --trace)
remote:  !
remote:  !     Precompiling assets failed.
remote:  !

**Comment by botnyst** [comment]
I am having the same issue, any update?

**Comment by frankis** [comment]
Did you check: https://devcenter.heroku.com/articles/rails-4-asset-pipeline?

**Comment by justthisguy** [comment]
It seems this is not just a Heroku problem. Where as I do get a similar problem on Heroku

> Sass::SyntaxError: Invalid CSS after ""sources": [": expected "|", was "],"   (in /tmp/..../vendor/bundle/ruby/2.2.0/bundler/gems/blogit 9e3876f3f028/app/assets/stylesheets/blogit/themes/default.css.map)    (sass):4

The same problem shows up when precompiling production assets locally.

> >RAILS_ENV=production bin/rake assets:precompile
> rake aborted!
> Sass::SyntaxError: Invalid CSS after ""sources": [": expected "|", was "],"
>   (in /Users/jtg/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/blogit-1.1.1/app/assets/stylesheets/blogit/themes/default.css.map)
> (sass):4

Some say this <code> [": expected "|", was "],"</code>  is a problem where scss is compiling less but that does not seem to be our problem.  

This does run find for me locally in development mode where there is no precompilation.

**Comment by Bodacious** [comment]
I think the issue here was caused by the `map` json files that were include in with the theme CSS.

I've removed these files—can you try installing the latest version and see if that fixes the issues?

``` ruby
gem "blogit", github: "katanacode/blogit", branch: "master"
```

**Comment by justthisguy** [comment]
@Bodacious, I gave that a try and everything looks great.  I precompiled locally and is running on Heroku.

**Comment by Bodacious** [comment]
@ken I'll keep that in mind when I'm working on the themes in future

Sorry for the slow response, I've been on vacation 

Gavin Morrice / Managing Director

Katana Code Ltd

www.katanacode.com

gavin@katanacode.com

+44 7787 432 733

---

This message is confidential and may contain privileged information. If it is not for you please inform us then delete it.

Any information in this message that does not relate to the official business of Katana Code is neither given nor endorsed by Katana Code. This e-mail does not constitute nor form part of a contract or unilateral obligation. Internet e-mails are not necessarily secure. Katana Code does not accept responsibility for changes made to this message after it was sent or viruses transmitted through this e-mail or any attachment. You should carry out your own virus checking procedure before opening any attachment to this e-mail. The e-mail and IT systems of Katana Code are subject to random monitoring and recording by or on behalf of Katana Code.

Katana Code is a trading name of Katana Code Ltd (Company No. SC410908), Registered Office: Lodge House, Priory Lane, Dunfermline KY12 7DT, +44 845 519 4329, www.katanacode.com
