### ISSUE TITLE
Issue with other routes when adding links to the blogit template.

### ISSUE THREAD

**Issue by jamesosb** [Bodacious/blogit#8]
Firstly, great gem! However, I'm currently having trouble with my routes when I use the Gem. I'm trying to add paths to link the blog to other parts of my app but am getting errors such as; 

```
     undefined local variable or method `destroy_user_session_path'  
```

Not sure if this is definitely the BlogIt gem but it only seems to be happening in these views.

Suggestions would be great!

James

**Comment by philou** [comment]
Hi James, thanks for using Blogit.
Where are you calling this method (it might be in you application controller or your application layout) ?

**Comment by jamesosb** [comment]
Hi Philou, It's being called in a partial which is pulled into my application layout. Thanks for your help so far!

**Comment by philou** [comment]
So, you can either set the blogit config option "inline_main_app_named_routes" to true, or you can prepend the call to your named route by "main_app." tell me how it goes.
Thanks

**Comment by jamesosb** [comment]
Great! This worked perfectly. Many thanks for all your help!

**Comment by omrishiv** [comment]
I'm having an issue with this too and I can't quite figure out how to fix it. I set inline_main_app_named_routes to true. I'm trying to call a form from a partial into my application layout. The form looks like:

<%= form_for :search, :url=>{:controller=>:static, :action=>:search}, :html=>{:class=>"navbar-search pull-left"} do |f|%>
    <%= f.text_field :term, :class=>"search-query span2", :placeholder=>"Search" %>
<% end %>

And the route: match 'static/search' => 'static#search'

I'm getting: No route matches {:controller=>"blogit/static", :action=>"search"}

ideas?

**Comment by omrishiv** [comment]
Ok, fixed it by hardcoding the url. Sorry to reopen this

**Comment by Bodacious** [comment]
Hi OmriShiv - You shouldn't have to hard-code the URL - It's not a very DRY solution.

If you're using the latest version of blogit and you've set `inline_main_app_named_routes` to **true** then this should work.

I'll have a look into this and get back to you.

Thanks for reporting this.

**Comment by omrishiv** [comment]
I  agree about it not being very DRY. Thanks for reopening. Let me know if I can provide any more information

**Comment by alex-kovshovik** [comment]
OmriShiv and Bodacious, I just had the same issue with inline_main_app_named_routes set to true, but with the different route. Here are a bit more details:

``` erb
<%= header_menu_item(:faq, link_to('Other Modalities', :controller => '/faq')) %>
```

The route for my FAQ page like this:

``` ruby
  resources :faq, :only => :index
```

This worked before I've mounted Blogit routes, now this fails with "No route matches {:controller=>"faq"}". The order of the Blogit routes in routes.rb doesn't matter - it failed either way.

Hard-coding the route URL works fine.

**Comment by Bodacious** [comment]
@OmriShiv why aren't you using named route helpers?

i.e. `faq_path`?

I'm not able to recreate this error - can anyone give me steps on how to do so?

**Comment by omrishiv** [comment]
@Bodacious this is @aspushkinus's issue, not mine. I'm having issues with blogit intercepting a call to another controller thinking it's its own.

**Comment by alex-kovshovik** [comment]
I would try to create sample application and repeat an issue, would provide steps if I could repeat this myself.

**Comment by Bodacious** [comment]
@OmriShiv sorry, I meant to address that to @aspushkinus

**Comment by alex-kovshovik** [comment]
@Bodacious I couldn't repeat the problem on the bare sample Rails application, but this not a significant issue for me, because I'm not using a lot of old-style link_to calls with controller/action - like you said, I'm using named route helpers. I've just changed those and it works!

If this becomes an issue - I'll just spend more time figuring it out and would submit a proper patch request if I can fix it.

Thank your for looking into this.

**Comment by Bodacious** [comment]
I'll close this one just now - I think it's reasonable to expect most Rails devs will be using route helper methods

**Comment by anjain** [comment]
![39185](https://cloud.githubusercontent.com/assets/633566/9519118/9a5d7a80-4cd9-11e5-9ac2-92821e555e41.jpg)
