### ISSUE TITLE
CSS themes

### ISSUE THREAD

**Issue by andy-chung** [Bodacious/blogit#80]
Appears in documentation that it is possible to provide CSS themes for blogit.  Kindly provide an example of doing it in Rails 4?
http://gavinmorrice.com/blog/
seems like it is already possible with above site.  Is the site in older version?  looks like there is not the description field in the above site.
Thanks.

**Comment by Bodacious** [comment]
Hi. I've added some docs for the themes here:
http://blogit.katanacode.com/doc/file.HowTo.html

At the moment, there's only one basic theme (the **default** theme). I'll add more themes when I can.

**Comment by Bodacious** [comment]
You can also see the default theme in action by running the `dummy` app within the gem's `spec` directory.
