### ISSUE TITLE
Need to Update readme for acts_as_taggable_on

### ISSUE THREAD

**Issue by Shehbaz** [Bodacious/blogit#81]
# For the latest versions :

rake acts_as_taggable_on_engine:install:migrations
# For versions 2.4.1 and earlier :

rails generate acts_as_taggable_on:migration

**Comment by johncip** [comment]
Came here to say this as well.

It might also be useful to mention in the main docs that for `rake blogit:seed` to work that at least one record for the chosen blogger class has to exist already. The error message makes that clear, of course, but why wait until someone sees an error?

**Comment by Bodacious** [comment]
@Shehbaz Thanks! This is now up to date

**Comment by Bodacious** [comment]
@johncip Thanks John, I'll update that now
