### ISSUE TITLE
acts as taggable install error

### ISSUE THREAD

**Issue by joshzandman** [Bodacious/blogit#85]
Hi there,

I'm getting the following error when trying to install/setup 'rake acts_as_taggable_on:install:migrations'

rake aborted!
Don't know how to build task 'acts_as_taggable_on:install:migrations'

Rails 4.2.4

**Comment by RodMal52** [comment]
Found the same error. It was addressed on another issue and you type this instead 

rake acts_as_taggable_on_engine:install:migrations

**Comment by pmaojo** [comment]
that´s it: rake acts_as_taggable_on_engine:install:migrations
Readme should be updated

**Comment by Bodacious** [comment]
@pmaojo thank you for pointing this out!
