### ISSUE TITLE
Reference blogit-admin throughout the docs

### ISSUE THREAD

**Issue by arnaudoff** [Bodacious/blogit#88]
Hello,

I believe it would be great if you could reference the dependency on `blogit-admin` gem in the installation instructions in the README.md and the detailed docs, because I've never used the gem before and it was only after I spent some hours researching and reading the source code that I found it is required [here](http://blogit.katanacode.com/doc/file.Upgrading.html).

Best wishes and thanks for the awesome gem!

**Comment by Bodacious** [comment]
Hi @arnaudoff 

I'm sorry to have cost you so much time. Adding a note to the README now.
