### ISSUE TITLE
Calling posts into other models

### ISSUE THREAD

**Issue by jamesosb** [Bodacious/blogit#9]
Hello! 

Sorry to write again so soon. I'm attempting to pull posts into another model (named locations). However whenever I try a simple @post = Post.all statement I get the following error:

```
uninitialized constant LocationsController::Post
```

Any suggestions for how this could be done?

Many Thanks!

**Comment by Bodacious** [comment]
James, blogit models are namespaced under the module Blogit

To access them in your app use 

```
Blogit::Post
```

**Comment by jamesosb** [comment]
Great! Cheers!
